# Generated by Django 3.2.16 on 2022-12-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('YAC', 'AC'), ('NAC', 'NO-AC'), ('LUX', 'LUXURIUS'), ('KIN', 'KING'), ('QUE', 'QUEEN'), ('YWI', 'WIFI'), ('NWI', 'NO-WIFI')], max_length=3)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
